// Exact student-expectation excerpts from TEKS.md, checked against TEA 19 TAC 112.43.
export const TEKS_SOURCE = 'https://tea.texas.gov/about-tea/laws-and-rules/sboe-rules-tac/sboe-tac-currently-in-effect/ch112c.pdf';
export const TEKS_REFERENCE = '19 TAC §112.43(c), Chemistry, Adopted 2020';
export const STANDARDS = {
  "C.1(A)": "ask questions and define problems based on observations or information from text, phenomena, models, or investigations;",
  "C.1(B)": "apply scientific practices to plan and conduct descriptive, comparative, and experimental investigations and use engineering practices to design solutions to problems;",
  "C.1(C)": "use appropriate safety equipment and practices during laboratory, classroom, and field investigations as outlined in Texas Education Agency-approved safety standards;",
  "C.1(D)": "use appropriate tools such as Safety Data Sheets (SDS), scientific or graphing calculators, computers and probes, electronic balances, an adequate supply of consumable chemicals, and sufficient scientific glassware such as beakers, Erlenmeyer flasks, pipettes, graduated cylinders, volumetric flasks, and burettes;",
  "C.1(E)": "collect quantitative data using the International System of Units (SI) and qualitative data as evidence;",
  "C.1(F)": "organize quantitative and qualitative data using oral or written lab reports, labeled drawings, particle diagrams, charts, tables, graphs, journals, summaries, or technology-based reports;",
  "C.1(G)": "develop and use models to represent phenomena, systems, processes, or solutions to engineering problems; and",
  "C.1(H)": "distinguish between scientific hypotheses, theories, and laws.",
  "C.2(A)": "identify advantages and limitations of models such as their size, scale, properties, and materials;",
  "C.2(B)": "analyze data by identifying significant statistical features, patterns, sources of error, and limitations;",
  "C.2(C)": "use mathematical calculations to assess quantitative relationships in data; and",
  "C.2(D)": "evaluate experimental and engineering designs.",
  "C.3(A)": "develop explanations and propose solutions supported by data and models and consistent with scientific ideas, principles, and theories;",
  "C.3(B)": "communicate explanations and solutions individually and collaboratively in a variety of settings and formats; and",
  "C.3(C)": "engage respectfully in scientific argumentation using applied scientific explanations and empirical evidence.",
  "C.4(A)": "analyze, evaluate, and critique scientific explanations and solutions by using empirical evidence, logical reasoning, and experimental and observational testing, so as to encourage critical thinking by the student;",
  "C.4(B)": "relate the impact of past and current research on scientific thought and society, including research methodology, cost-benefit analysis, and contributions of diverse scientists as related to the content; and",
  "C.4(C)": "research and explore resources such as museums, libraries, professional organizations, private companies, online platforms, and mentors employed in a science, technology, engineering, and mathematics (STEM) field in order to investigate STEM careers.",
  "C.5(A)": "explain the development of the Periodic Table over time using evidence such as chemical and physical properties;",
  "C.5(B)": "predict the properties of elements in chemical families, including alkali metals, alkaline earth metals, halogens, noble gases, and transition metals, based on valence electrons patterns using the Periodic Table; and",
  "C.5(C)": "analyze and interpret elemental data, including atomic radius, atomic mass, electronegativity, ionization energy, and reactivity to identify periodic trends.",
  "C.6(A)": "construct models using Dalton's Postulates, Thomson's discovery of electron properties, Rutherford's nuclear atom, Bohr's nuclear atom, and Heisenberg's Uncertainty Principle to show the development of modern atomic theory over time;",
  "C.6(B)": "describe the structure of atoms and ions, including the masses, electrical charges, and locations of protons and neutrons in the nucleus and electrons in the electron cloud;",
  "C.6(C)": "investigate the mathematical relationship between energy, frequency, and wavelength of light using the electromagnetic spectrum and relate it to the quantization of energy in the emission spectrum;",
  "C.6(D)": "calculate average atomic mass of an element using isotopic composition; and",
  "C.6(E)": "construct models to express the arrangement of electrons in atoms of representative elements using electron configurations and Lewis dot structures.",
  "C.7(A)": "construct an argument to support how periodic trends such as electronegativity can predict bonding between elements;",
  "C.7(B)": "name and write the chemical formulas for ionic and covalent compounds using International Union of Pure and Applied Chemistry (IUPAC) nomenclature rules;",
  "C.7(C)": "classify and draw electron dot structures for molecules with linear, bent, trigonal planar, trigonal pyramidal, and tetrahedral molecular geometries as explained by Valence Shell Electron Pair Repulsion (VSEPR) theory; and",
  "C.7(D)": "analyze the properties of ionic, covalent, and metallic substances in terms of intramolecular and intermolecular forces.",
  "C.8(A)": "define mole and apply the concept of molar mass to convert between moles and grams;",
  "C.8(B)": "calculate the number of atoms or molecules in a sample of material using Avogadro's number;",
  "C.8(C)": "calculate percent composition of compounds; and",
  "C.8(D)": "differentiate between empirical and molecular formulas.",
  "C.9(A)": "interpret, write, and balance chemical equations, including synthesis, decomposition, single replacement, double replacement, and combustion reactions using the law of conservation of mass;",
  "C.9(B)": "differentiate among acid-base reactions, precipitation reactions, and oxidation-reduction reactions;",
  "C.9(C)": "perform stoichiometric calculations, including determination of mass relationships, gas volume relationships, and percent yield; and",
  "C.9(D)": "describe the concept of limiting reactants in a balanced chemical equation.",
  "C.10(A)": "describe the postulates of the kinetic molecular theory;",
  "C.10(B)": "describe and calculate the relationships among volume, pressure, number of moles, and temperature for an ideal gas; and",
  "C.10(C)": "define and apply Dalton's law of partial pressure.",
  "C.11(A)": "describe the unique role of water in solutions in terms of polarity;",
  "C.11(B)": "distinguish among types of solutions, including electrolytes and nonelectrolytes and unsaturated, saturated, and supersaturated solutions;",
  "C.11(C)": "investigate how solid and gas solubilities are influenced by temperature using solubility curves and how rates of dissolution are influenced by temperature, agitation, and surface area;",
  "C.11(D)": "investigate the general rules regarding solubility and predict the solubility of the products of a double replacement reaction;",
  "C.11(E)": "calculate the concentration of solutions in units of molarity; and",
  "C.11(F)": "calculate the dilutions of solutions using molarity.",
  "C.12(A)": "name and write the chemical formulas for acids and bases using IUPAC nomenclature rules;",
  "C.12(B)": "define acids and bases and distinguish between Arrhenius and Bronsted-Lowry definitions;",
  "C.12(C)": "differentiate between strong and weak acids and bases;",
  "C.12(D)": "predict products in acid-base reactions that form water; and",
  "C.12(E)": "define pH and calculate the pH of a solution using the hydrogen ion concentration.",
  "C.13(A)": "explain everyday examples that illustrate the four laws of thermodynamics;",
  "C.13(B)": "investigate the process of heat transfer using calorimetry;",
  "C.13(C)": "classify processes as exothermic or endothermic and represent energy changes that occur in chemical reactions using thermochemical equations or graphical analysis; and",
  "C.13(D)": "perform calculations involving heat, mass, temperature change, and specific heat.",
  "C.14(A)": "describe the characteristics of alpha, beta, and gamma radioactive decay processes in terms of balanced nuclear equations;",
  "C.14(B)": "compare fission and fusion reactions; and",
  "C.14(C)": "give examples of applications of nuclear phenomena such as nuclear stability, radiation therapy, diagnostic imaging, solar cells, and nuclear power."
};
