/*
 * Notation sheet: every notation shared/js/notation.js handles, rendered on one page.
 *
 * The reason this exists is the reason contact-sheet.mjs exists. The node suite
 * (tests/notation.test.mjs) proves the MARKUP is right -- that H2O becomes
 * H<sub>2</sub>O and that "Bronsted-Lowry" is left alone. It cannot see whether a
 * subscript is legible at 14px, whether a nuclide's two numbers actually stack, or whether
 * a paragraph of formulas jumps line to line. That still needs eyes, and eyes need one page.
 *
 * Every row is generated by calling the real module, so the sheet cannot drift from the
 * code. Each row shows the authored source beside the rendered result.
 *
 * Usage, from the repo root:
 *   node units_new/tools/notation-sheet.mjs            writes units_new/tools/notation-sheet.html
 *   node units_new/tools/notation-sheet.mjs --open     ...and prints the file:// URL
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  formulaHTML, configHTML, sciHTML, notationHTML, escapeHTML
} from '../../shared/js/notation.js';
import { REACTIONS } from '../06-reactions-stoichiometry/js/model.js';
import { FAMILIES } from '../03-periodic-trends/js/model.js';
import { electronConfiguration, formatConfig } from '../../shared/js/chem.js';

const HERE = dirname(fileURLToPath(import.meta.url));

// [heading, renderer, [source strings]]
const SECTIONS = [
  ['Formulas', formulaHTML, [
    'H2O', 'Fe2O3', 'Ca(OH)2', 'Cu(NO3)2', 'CH3COOH', 'C6H12O6', 'Al2(SO4)3', 'CuSO4·5H2O',
  ]],
  ['Ions and charges', formulaHTML, [
    'H+', 'OH^-', 'NH4+', 'SO4^2-', 'PO4^3-', 'Ca2+', 'HCO3^-', 'CH3COO^-',
  ]],
  ['Equations — the reported defect was the first of these', formulaHTML, [
    ...FAMILIES.filter(f => f.reaction).map(f => f.reaction),
    'H2CO3 <=> H+ + HCO3^-',
    'AgNO3(aq) + NaCl(aq) -> AgCl v + NaNO3(aq)',
    'CaCl2(s) -> Ca^2+(aq) + 2Cl^-(aq)',
  ]],
  ['Equations from the models, through the KaTeX-less fallback', formulaHTML,
    REACTIONS.map(r => r.display)],
  ['Electron configurations — the digit AFTER the letter is the one that rises', configHTML,
    [12, 24, 29, 26, 35].map(z => formatConfig(electronConfiguration(z)))
      .concat(['[Ne] 3s2', '[Ar] 4s1 3d5', '[Xe] 6s1 4f14 5d10'])],
  ['Nuclides — mass number over atomic number, in front of the symbol', formulaHTML, [
    '^{235}_{92}U', '^{99m}_{43}Tc', '^{0}_{-1}e',
    '^{2}_{1}H + ^{3}_{1}H -> ^{4}_{2}He + ^{1}_{0}n',
    '^{235}_{92}U + ^{1}_{0}n -> ^{99}_{42}Mo + ^{135}_{50}Sn + 2^{1}_{0}n',
  ]],
  ['Scientific notation', v => sciHTML(Number(v), { sig: 4 }), [
    '6.022e23', '1.882e24', '1.8e-5', '3.0e-8', '6.626e-34', '0.5', '22.4',
  ]],
  ['Prose — what the marker rewrites', notationHTML, [
    'You filed 1.88e+24 against 3.76e+24 particles.',
    "Avogadro's number is 6.022e23 representative particles in one mole.",
    'From pH 6.5 to 2.5 is 4 units, so 10^4, about ten thousand times more acidic.',
    'It works out to 12.3 g H2O, and the excess is Fe2O3.',
    'A base is any substance that produces OH- ions when dissolved in water.',
  ]],
  ['Prose — what it must leave alone', notationHTML, [
    'Interpret, write, and balance equations using conservation of mass. TEKS C.9(A)',
    'Bronsted-Lowry defines an acid as a proton donor, with no need for water.',
    'There is NO free element on the left, so there is nothing to swap.',
    'C-14 at 70% over 3000 y, Sr-90 at 79% over a decade, I-131 in a thyroid.',
    'The cylinder read 200 atm at dawn and 215 on the deck. Day 3 of 12, at 06:00.',
    'fill="#0e2836" stroke="#1e5b66"',
  ]],
];

const rows = SECTIONS.map(([title, render, items]) => `
  <section>
    <h2>${escapeHTML(title)}</h2>
    <table>
      <thead><tr><th>authored source</th><th>rendered</th></tr></thead>
      <tbody>${items.map(s => `
        <tr>
          <td class="src">${escapeHTML(s)}</td>
          <td class="out">${render(s)}</td>
        </tr>`).join('')}
      </tbody>
    </table>
  </section>`).join('');

// A paragraph of formulas at body size, because the one thing a table cannot show is whether
// the line box grows: if sub/sup are left on the UA's vertical-align, these lines drift apart.
const FLOW = notationHTML(
  'The garage reading comes to 12.3 g H2, which is 3.68e23 particles, and the shelf still holds '
  + 'CH3COOH beside HCl while the drum takes Ca(OH)2 against H2SO4 at 1.8e-5. '
  + 'Every line in this paragraph has to sit on the same rhythm as one with no formulas in it '
  + 'at all, or a page of consequence text reads as though it were set by hand.');

const html = `<!doctype html>
<meta charset="utf-8">
<title>Notation sheet</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:wght@400;700&family=Bitter:wght@600;700&family=JetBrains+Mono:wght@500;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="../../shared/css/tokens.css">
<link rel="stylesheet" href="../../shared/css/base.css">
<style>
  body { max-width: 1000px; margin: 0 auto; padding: 32px 24px 64px; }
  h1 { margin-bottom: 4px; }
  .lede { color: var(--muted); margin: 0 0 32px; max-width: 62ch; }
  section { margin-bottom: 36px; }
  h2 { font-size: var(--fs-md); margin: 0 0 10px; }
  table { width: 100%; border-collapse: collapse; }
  th { text-align: left; font-size: var(--fs-xs); text-transform: uppercase;
       letter-spacing: .1em; color: var(--muted); font-weight: 500;
       border-bottom: 1px solid var(--line, #d6e0e4); padding: 4px 10px; }
  td { padding: 7px 10px; border-bottom: 1px solid rgba(0,0,0,.06); vertical-align: baseline; }
  td.src { font-family: var(--font-mono); font-size: var(--fs-xs); color: var(--muted);
           width: 46%; word-break: break-all; }
  td.out { font-size: 16px; }
  .flow { border-left: 3px solid var(--accent, #2a7d8a); padding: 2px 0 2px 16px; max-width: 68ch; }
  .flow p { margin: 0 0 8px; }
</style>
<h1>Notation sheet</h1>
<p class="lede">Every notation <code>shared/js/notation.js</code> produces, rendered by the real
module in the real stylesheet. The node suite proves the markup; this page is for the half that
needs eyes — legibility at size, whether a nuclide's numbers really stack, and whether a
paragraph of formulas keeps its line rhythm.</p>
${rows}
<section>
  <h2>Line rhythm — these two paragraphs must sit on the same baseline grid</h2>
  <div class="flow">
    <p>${FLOW}</p>
    <p>The garage reading comes to a round number, which is a plain count of particles, and the
    shelf still holds vinegar beside acid while the drum takes lime against sulfuric at a small
    constant. Every line in this paragraph has to sit on the same rhythm as one with no formulas
    in it at all, or a page of consequence text reads as though it were set by hand.</p>
  </div>
</section>
`;

const out = join(HERE, 'notation-sheet.html');
writeFileSync(out, html, 'utf8');
const rowCount = SECTIONS.reduce((n, s) => n + s[2].length, 0);
console.log(`notation-sheet.html written: ${SECTIONS.length} sections, ${rowCount} rows`);
if (process.argv.includes('--open')) console.log(`file:///${out.replace(/\\/g, '/')}`);
